name: C/C++ CI
"SAP_Java_version": "17.0.11"
"SAP_Java_release": "6"
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download SAP Java JDK
      run: |
        curl -L -o sapmachine-jdk.tar.gz https://github.com/SAP/SapMachine/releases/download/sapmachine-%7BSAP_Java_version%7D%2B%7BSAP_Java_release%7D/sapmachine-test    - uses: actions/checkout@v4
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
              - name: Download Release Asset
                uses: fabriciobastian/download-release-asset-action@v1.0.6
            
