name: Makefile CI
env:
  SAP_Java_version: "17.0.11"
  SAP_Java_release: "6"
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Echo user inputs at runtime
      run: echo "Current log level is ${{ github.event.inputs.logLevel }}" 
      
    - name: Download SAP Java JDK
      run: |
        curl -L -o sapmachine-jdk.tar.gz https://github.com/SAP/SapMachine/releases/download/sapmachine-"$SAP_Java_version"%2B"$SAP_Java_release"/sapmachine-jdk-"$SAP_Java_version"-ea."$SAP_Java_release"_linux-x64_bin.tar.gz

    - name: Creating setup-workspace summary
      run: echo -e "### Hello world! 🚀 \n The log level was set to ${{ github.event.inputs.logLevel }} \n another option = bla bla /n " >> $GITHUB_STEP_SUMMARY
    
    - name: Install dependencies
      run: sudo apt-get install -y git automake build-essential libasound2 libasound2-dev libpulse0 libpulse-dev libjack0 libjack-dev

    - name: Execute autogen.sh
      run: ./autogen.sh
      
    - name: Execute configure
      run: ./configure 

    - name: Execute make command
      run: make

    - name: Run check
      run: make check

    - uses: actions/upload-artifact@v4
      with:
        name: vban_receptor
        path: /home/runner/work/vban-compiled/vban-compiled/src/vban_receptor
