name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: sudo apt-get install -y git automake build-essential libasound2 libasound2-dev libpulse0 libpulse-dev libjack0 libjack-dev

    - name: Execute autogen.sh
      run: ./autogen.sh
      
    - name: Execute configure
      run: ./configure 

    - name: Execute make command
      run: make

    - name: Run check
      run: make check

    - uses: actions/upload-artifact@v4
      with:
        name: vban_receptor
        path: /home/runner/work/vban-compiled/vban-compiled/src/vban_receptor
