name: Makefile CI
env:
  SAP_Java_version: "17.0.11"
  SAP_Java_release: "6"
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Download SAP Java JDK
      run: |
        curl -L -o sapmachine-jdk.tar.gz https://github.com/SAP/SapMachine/releases/download/sapmachine-"$SAP_Java_version"%2B"$SAP_Java_release"/sapmachine-jdk-"$SAP_Java_version"-ea."$SAP_Java_release"_linux-x64_bin.tar.gz

    - name: Adding markdown
      run: echo '### Hello world! 🚀' >> $GITHUB_STEP_SUMMARY
    
    - name: Install dependencies
      run: sudo apt-get install -y git automake build-essential libasound2 libasound2-dev libpulse0 libpulse-dev libjack0 libjack-dev

    - name: Execute autogen.sh
      run: ./autogen.sh
      
    - name: Execute configure
      run: ./configure 

    - name: Execute make command
      run: make

    - name: Run check
      run: make check

    - uses: actions/upload-artifact@v4
      with:
        name: vban_receptor
        path: /home/runner/work/vban-compiled/vban-compiled/src/vban_receptor
